# Generated by Django 5.0.7 on 2024-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_icon', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=50)),
                ('release_date', models.DateField(max_length=50)),
                ('description', models.TextField()),
                ('actor', models.TextField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
