# Generated by Django 5.0.7 on 2024-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_icon',
            field=models.FileField(upload_to='movie_icons/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
    ]
